export enum INITIAL {
  START = 'INTITAL_APPL_START',
  END = 'INTITAL_APPL_END',
  FAIL = 'INTITAL_APPL_FAIL',
  CLEAR = 'CLEAR_APP',
}

export enum ERROR {
  NORMAL_RISE = 'ERROR_NORMAL_RISE',
  NORMAL_HIDE = 'ERROR_NORMAL_HIDE',
  NETWORK_RISE = 'ERROR_NETWORK_RISE',
  NETWORK_HIDE = 'ERROR_NETWORK_HIDE',
}

export enum LOGIN {
  START = 'LOGIN_START',
  END = 'LOGIN_START_END',
  FAIL = 'LOGIN_START_FAIL',
}

export enum LOGIN_EXTERNAL {
  START = 'LOGIN_EXTERNAL_START',
  END = 'LOGIN_EXTERNAL_END',
  FAIL = 'LOGIN_EXTERNAL_FAIL',
}

export enum REGISTER {
  START = 'REGISTER_START',
  END = 'REGISTER_END',
  FAIL = 'REGISTER_FAIL',
}

export enum LOGOUT {
  START = 'LOGOUT_START',
  END = 'LOGOUT_END',
  FAIL = 'LOGOUT_FAIL',
}

export enum CLEAR {
  USER = 'CLEAR_USER',
  MESSAGE = 'CLEAR_MESSAGE',
}

export enum GROUPCHAT {
  START = 'GROUPCHAT_START',
  END = 'GROUPCHAT_END',
  UPDATE = 'GROUPCHAT_UPDATE',
  FAIL = 'GROUPCHAT_FAIL',
  UPDATE_LATEST_MESSAGE = 'UPDATE_LATEST_MESSAGE',
  CLEAR = 'GROUPCHAT_CLEAR',
}

export enum GET_REQUEST_LIST {
  START = 'GET-REQUEST-LIST-START',
  END = 'GET-REQUEST-LIST-END',
  FAIL = 'GET-REQUEST-LIST-FAIL',
}

export enum LIST_CHAT {
  MERGE = 'MERGE-LIST-CHAT-DATA',
  ADD = 'ADD-LIST-CHAT-DATA',
  LOADMORE_START = 'LOAD-MORE-CHAT-DATA-start',
  LOADMORE_END = 'LOAD-MORE-CHAT-DATA-end',
  LOADMORE_FAIL = 'LOAD-MORE-CHAT-DATA-fail',
  LOADMORE_CLEAR = 'LOAD-MORE-CLEAR-DATA',
}

export enum FRIENDLIST {
  START = 'FRIENDLIST_START',
  END = 'FRIENDLIST_END',
  FAIL = 'FRIENDLIST_FAIL',
}

export enum GET_DETAIL_USER {
  START = 'GET-DETAIL-USER-START',
  END = 'GET-DETAIL-USER-END',
  FAIL = 'GET-DETAIL-USER-FAIL',
}
