export const SET_API_INIT = 'SET_API_INIT';

export const REGISTER_USERS = 'REGISTER_USERS';
export const REGISTER_USERS_SUCCESS = 'REGISTER_USERS_SUCCESS';
export const REGISTER_USERS_FAILED = 'REGISTER_USERS_FAILED';
